spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.207:3306/sharebook?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sharebook
logging:
  level:
    com.myself.sbdiancan.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.github.myself.entity